
--https://dl.ncsbe.gov/?prefix=data/Snapshots/
CREATE TABLE public.ncvoter_all
(
  county_id text,
  county_desc text,
  voter_reg_num text,
  status_cd text,
  voter_status_desc text,
  reason_cd text,
  voter_status_reason_desc text,
  absent_ind text,
  name_prefx_cd text,
  last_name text,
  first_name text,
  middle_name text,
  name_suffix_lbl text,
  res_street_address text,
  res_city_desc text,
  state_cd text,
  zip_code text,
  mail_addr1 text,
  mail_addr2 text,
  mail_addr3 text,
  mail_addr4 text,
  mail_city text,
  mail_state text,
  mail_zipcode text,
  full_phone_number text,
  race_code text,
  ethnic_code text,
  party_cd text,
  gender_code text,
  birth_age text,
  birth_state text,
  drivers_lic text,
  registr_dt text,
  precinct_abbrv text,
  precinct_desc text,
  municipality_abbrv text,
  municipality_desc text,
  ward_abbrv text,
  ward_desc text,
  cong_dist_abbrv text,
  super_court_abbrv text,
  judic_dist_abbrv text,
  nc_senate_abbrv text,
  nc_house_abbrv text,
  county_commiss_abbrv text,
  county_commiss_desc text,
  township_abbrv text,
  township_desc text,
  school_dist_abbrv text,
  school_dist_desc text,
  fire_dist_abbrv text,
  fire_dist_desc text,
  water_dist_abbrv text,
  water_dist_desc text,
  sewer_dist_abbrv text,
  sewer_dist_desc text,
  sanit_dist_abbrv text,
  sanit_dist_desc text,
  rescue_dist_abbrv text,
  rescue_dist_desc text,
  munic_dist_abbrv text,
  munic_dist_desc text,
  dist_1_abbrv text,
  dist_1_desc text,
  dist_2_abbrv text,
  dist_2_desc text,
  confidential_ind text,
  birth_year int,
  ncid text,
  vtd_abbrv text,
  vtd_desc text
);

COPY public.ncvoter_all FROM '/data/ncvr/ncvoter_Statewide.txt' DELIMITER E'\t' CSV HEADER ENCODING 'LATIN1' QUOTE E'\"' ESCAPE E'\"'
